#include "duktape.h"
// AUTOGENERATED CODE: DO NOT EDIT. YOUR CHANGES WILL BE LOST.
#ifdef _WIN32
#define WRAPPED_EXPORT_CALL __declspec(dllexport)
#else
#define WRAPPED_EXPORT_CALL
#endif

WRAPPED_EXPORT_CALL void * public_duk_alloc(duk_context * ctx, duk_size_t size)
{
	return duk_alloc(ctx, size);
}

WRAPPED_EXPORT_CALL void * public_duk_alloc_raw(duk_context * ctx, duk_size_t size)
{
	return duk_alloc_raw(ctx, size);
}

WRAPPED_EXPORT_CALL void public_duk_base64_decode(duk_context * ctx, duk_idx_t index)
{
	duk_base64_decode(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_base64_encode(duk_context * ctx, duk_idx_t index)
{
	return duk_base64_encode(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_call(duk_context * ctx, duk_idx_t nargs)
{
	duk_call(ctx, nargs);
}

WRAPPED_EXPORT_CALL void public_duk_call_method(duk_context * ctx, duk_idx_t nargs)
{
	duk_call_method(ctx, nargs);
}

WRAPPED_EXPORT_CALL void public_duk_call_prop(duk_context * ctx, duk_idx_t obj_index, duk_idx_t nargs)
{
	duk_call_prop(ctx, obj_index, nargs);
}

WRAPPED_EXPORT_CALL duk_codepoint_t public_duk_char_code_at(duk_context * ctx, duk_idx_t index, duk_size_t char_offset)
{
	return duk_char_code_at(ctx, index, char_offset);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_check_stack(duk_context * ctx, duk_idx_t extra)
{
	return duk_check_stack(ctx, extra);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_check_stack_top(duk_context * ctx, duk_idx_t top)
{
	return duk_check_stack_top(ctx, top);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_check_type(duk_context * ctx, duk_idx_t index, duk_int_t type)
{
	return duk_check_type(ctx, index, type);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_check_type_mask(duk_context * ctx, duk_idx_t index, duk_uint_t mask)
{
	return duk_check_type_mask(ctx, index, mask);
}

WRAPPED_EXPORT_CALL void public_duk_compact(duk_context * ctx, duk_idx_t obj_index)
{
	duk_compact(ctx, obj_index);
}

WRAPPED_EXPORT_CALL void public_duk_compile(duk_context * ctx, duk_uint_t flags)
{
	duk_compile(ctx, flags);
}

WRAPPED_EXPORT_CALL void public_duk_compile_file(duk_context * ctx, duk_uint_t flags, const char * path)
{
	duk_compile_file(ctx, flags, path);
}

WRAPPED_EXPORT_CALL void public_duk_compile_lstring(duk_context * ctx, duk_uint_t flags, const char * src, duk_size_t len)
{
	duk_compile_lstring(ctx, flags, src, len);
}

WRAPPED_EXPORT_CALL void public_duk_compile_lstring_filename(duk_context * ctx, duk_uint_t flags, const char * src, duk_size_t len)
{
	duk_compile_lstring_filename(ctx, flags, src, len);
}

WRAPPED_EXPORT_CALL void public_duk_compile_string(duk_context * ctx, duk_uint_t flags, const char * src)
{
	duk_compile_string(ctx, flags, src);
}

WRAPPED_EXPORT_CALL void public_duk_compile_string_filename(duk_context * ctx, duk_uint_t flags, const char * src)
{
	duk_compile_string_filename(ctx, flags, src);
}

WRAPPED_EXPORT_CALL void public_duk_concat(duk_context * ctx, duk_idx_t count)
{
	duk_concat(ctx, count);
}

WRAPPED_EXPORT_CALL void public_duk_copy(duk_context * ctx, duk_idx_t from_index, duk_idx_t to_index)
{
	duk_copy(ctx, from_index, to_index);
}

WRAPPED_EXPORT_CALL duk_context * public_duk_create_heap(duk_alloc_function alloc_func, duk_realloc_function realloc_func, duk_free_function free_func, void * heap_udata, duk_fatal_function fatal_handler)
{
	return duk_create_heap(alloc_func, realloc_func, free_func, heap_udata, fatal_handler);
}

WRAPPED_EXPORT_CALL duk_context * public_duk_create_heap_default()
{
	return duk_create_heap_default();
}

WRAPPED_EXPORT_CALL void public_duk_debugger_attach(duk_context * ctx, duk_debug_read_function read_cb, duk_debug_write_function write_cb, duk_debug_peek_function peek_cb, duk_debug_read_flush_function read_flush_cb, duk_debug_write_flush_function write_flush_cb, duk_debug_detached_function detached_cb, void * udata)
{
	duk_debugger_attach(ctx, read_cb, write_cb, peek_cb, read_flush_cb, write_flush_cb, detached_cb, udata);
}

WRAPPED_EXPORT_CALL void public_duk_debugger_cooperate(duk_context * ctx)
{
	duk_debugger_cooperate(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_debugger_detach(duk_context * ctx)
{
	duk_debugger_detach(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_decode_string(duk_context * ctx, duk_idx_t index, duk_decode_char_function callback, void * udata)
{
	duk_decode_string(ctx, index, callback, udata);
}

WRAPPED_EXPORT_CALL void public_duk_def_prop(duk_context * ctx, duk_idx_t obj_index, duk_uint_t flags)
{
	duk_def_prop(ctx, obj_index, flags);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_del_prop(duk_context * ctx, duk_idx_t obj_index)
{
	return duk_del_prop(ctx, obj_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_del_prop_index(duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
{
	return duk_del_prop_index(ctx, obj_index, arr_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_del_prop_string(duk_context * ctx, duk_idx_t obj_index, const char * key)
{
	return duk_del_prop_string(ctx, obj_index, key);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_del_var(duk_context * ctx)
{
	return duk_del_var(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_destroy_heap(duk_context * ctx)
{
	duk_destroy_heap(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_dump_context_stderr(duk_context * ctx)
{
	duk_dump_context_stderr(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_dump_context_stdout(duk_context * ctx)
{
	duk_dump_context_stdout(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_dup(duk_context * ctx, duk_idx_t from_index)
{
	duk_dup(ctx, from_index);
}

WRAPPED_EXPORT_CALL void public_duk_dup_top(duk_context * ctx)
{
	duk_dup_top(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_enum(duk_context * ctx, duk_idx_t obj_index, duk_uint_t enum_flags)
{
	duk_enum(ctx, obj_index, enum_flags);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_equals(duk_context * ctx, duk_idx_t index1, duk_idx_t index2)
{
	return duk_equals(ctx, index1, index2);
}

WRAPPED_EXPORT_CALL void public_duk_error_va(duk_context * ctx, duk_errcode_t err_code, const char * fmt, va_list ap)
{
	duk_error_va(ctx, err_code, fmt, ap);
}

WRAPPED_EXPORT_CALL void public_duk_eval(duk_context * ctx)
{
	duk_eval(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_eval_file(duk_context * ctx, const char * path)
{
	duk_eval_file(ctx, path);
}

WRAPPED_EXPORT_CALL void public_duk_eval_file_noresult(duk_context * ctx, const char * path)
{
	duk_eval_file_noresult(ctx, path);
}

WRAPPED_EXPORT_CALL void public_duk_eval_lstring(duk_context * ctx, const char * src, duk_size_t len)
{
	duk_eval_lstring(ctx, src, len);
}

WRAPPED_EXPORT_CALL void public_duk_eval_lstring_noresult(duk_context * ctx, const char * src, duk_size_t len)
{
	duk_eval_lstring_noresult(ctx, src, len);
}

WRAPPED_EXPORT_CALL void public_duk_eval_noresult(duk_context * ctx)
{
	duk_eval_noresult(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_eval_string(duk_context * ctx, const char * src)
{
	duk_eval_string(ctx, src);
}

WRAPPED_EXPORT_CALL void public_duk_eval_string_noresult(duk_context * ctx, const char * src)
{
	duk_eval_string_noresult(ctx, src);
}

WRAPPED_EXPORT_CALL void public_duk_fatal(duk_context * ctx, duk_errcode_t err_code, const char * err_msg)
{
	duk_fatal(ctx, err_code, err_msg);
}

WRAPPED_EXPORT_CALL void public_duk_free(duk_context * ctx, void * ptr)
{
	duk_free(ctx, ptr);
}

WRAPPED_EXPORT_CALL void public_duk_free_raw(duk_context * ctx, void * ptr)
{
	duk_free_raw(ctx, ptr);
}

WRAPPED_EXPORT_CALL void public_duk_gc(duk_context * ctx, duk_uint_t flags)
{
	duk_gc(ctx, flags);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_get_boolean(duk_context * ctx, duk_idx_t index)
{
	return duk_get_boolean(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_get_buffer(duk_context * ctx, duk_idx_t index, duk_size_t * out_size)
{
	return duk_get_buffer(ctx, index, out_size);
}

WRAPPED_EXPORT_CALL duk_context * public_duk_get_context(duk_context * ctx, duk_idx_t index)
{
	return duk_get_context(ctx, index);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_get_current_magic(duk_context * ctx)
{
	return duk_get_current_magic(ctx);
}

WRAPPED_EXPORT_CALL duk_c_function public_duk_get_c_function(duk_context * ctx, duk_idx_t index)
{
	return duk_get_c_function(ctx, index);
}

WRAPPED_EXPORT_CALL duk_errcode_t public_duk_get_error_code(duk_context * ctx, duk_idx_t index)
{
	return duk_get_error_code(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_get_finalizer(duk_context * ctx, duk_idx_t index)
{
	duk_get_finalizer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_get_global_string(duk_context * ctx, const char * key)
{
	return duk_get_global_string(ctx, key);
}

WRAPPED_EXPORT_CALL void * public_duk_get_heapptr(duk_context * ctx, duk_idx_t index)
{
	return duk_get_heapptr(ctx, index);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_get_int(duk_context * ctx, duk_idx_t index)
{
	return duk_get_int(ctx, index);
}

WRAPPED_EXPORT_CALL duk_size_t public_duk_get_length(duk_context * ctx, duk_idx_t index)
{
	return duk_get_length(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_get_lstring(duk_context * ctx, duk_idx_t index, duk_size_t * out_len)
{
	return duk_get_lstring(ctx, index, out_len);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_get_magic(duk_context * ctx, duk_idx_t index)
{
	return duk_get_magic(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_get_memory_functions(duk_context * ctx, duk_memory_functions * out_funcs)
{
	duk_get_memory_functions(ctx, out_funcs);
}

WRAPPED_EXPORT_CALL duk_double_t public_duk_get_number(duk_context * ctx, duk_idx_t index)
{
	return duk_get_number(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_get_pointer(duk_context * ctx, duk_idx_t index)
{
	return duk_get_pointer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_get_prop(duk_context * ctx, duk_idx_t obj_index)
{
	return duk_get_prop(ctx, obj_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_get_prop_index(duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
{
	return duk_get_prop_index(ctx, obj_index, arr_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_get_prop_string(duk_context * ctx, duk_idx_t obj_index, const char * key)
{
	return duk_get_prop_string(ctx, obj_index, key);
}

WRAPPED_EXPORT_CALL void public_duk_get_prototype(duk_context * ctx, duk_idx_t index)
{
	duk_get_prototype(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_get_string(duk_context * ctx, duk_idx_t index)
{
	return duk_get_string(ctx, index);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_get_top(duk_context * ctx)
{
	return duk_get_top(ctx);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_get_top_index(duk_context * ctx)
{
	return duk_get_top_index(ctx);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_get_type(duk_context * ctx, duk_idx_t index)
{
	return duk_get_type(ctx, index);
}

WRAPPED_EXPORT_CALL duk_uint_t public_duk_get_type_mask(duk_context * ctx, duk_idx_t index)
{
	return duk_get_type_mask(ctx, index);
}

WRAPPED_EXPORT_CALL duk_uint_t public_duk_get_uint(duk_context * ctx, duk_idx_t index)
{
	return duk_get_uint(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_get_var(duk_context * ctx)
{
	duk_get_var(ctx);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_has_prop(duk_context * ctx, duk_idx_t obj_index)
{
	return duk_has_prop(ctx, obj_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_has_prop_index(duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
{
	return duk_has_prop_index(ctx, obj_index, arr_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_has_prop_string(duk_context * ctx, duk_idx_t obj_index, const char * key)
{
	return duk_has_prop_string(ctx, obj_index, key);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_has_var(duk_context * ctx)
{
	return duk_has_var(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_hex_decode(duk_context * ctx, duk_idx_t index)
{
	duk_hex_decode(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_hex_encode(duk_context * ctx, duk_idx_t index)
{
	return duk_hex_encode(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_insert(duk_context * ctx, duk_idx_t to_index)
{
	duk_insert(ctx, to_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_array(duk_context * ctx, duk_idx_t index)
{
	return duk_is_array(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_boolean(duk_context * ctx, duk_idx_t index)
{
	return duk_is_boolean(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_bound_function(duk_context * ctx, duk_idx_t index)
{
	return duk_is_bound_function(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_buffer(duk_context * ctx, duk_idx_t index)
{
	return duk_is_buffer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_callable(duk_context * ctx, duk_idx_t index)
{
	return duk_is_callable(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_constructor_call(duk_context * ctx)
{
	return duk_is_constructor_call(ctx);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_c_function(duk_context * ctx, duk_idx_t index)
{
	return duk_is_c_function(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_dynamic_buffer(duk_context * ctx, duk_idx_t index)
{
	return duk_is_dynamic_buffer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_ecmascript_function(duk_context * ctx, duk_idx_t index)
{
	return duk_is_ecmascript_function(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_error(duk_context * ctx, duk_idx_t index)
{
	return duk_is_error(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_fixed_buffer(duk_context * ctx, duk_idx_t index)
{
	return duk_is_fixed_buffer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_function(duk_context * ctx, duk_idx_t index)
{
	return duk_is_function(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_lightfunc(duk_context * ctx, duk_idx_t index)
{
	return duk_is_lightfunc(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_nan(duk_context * ctx, duk_idx_t index)
{
	return duk_is_nan(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_null(duk_context * ctx, duk_idx_t index)
{
	return duk_is_null(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_null_or_undefined(duk_context * ctx, duk_idx_t index)
{
	return duk_is_null_or_undefined(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_number(duk_context * ctx, duk_idx_t index)
{
	return duk_is_number(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_object(duk_context * ctx, duk_idx_t index)
{
	return duk_is_object(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_object_coercible(duk_context * ctx, duk_idx_t index)
{
	return duk_is_object_coercible(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_pointer(duk_context * ctx, duk_idx_t index)
{
	return duk_is_pointer(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_primitive(duk_context * ctx, duk_idx_t index)
{
	return duk_is_primitive(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_strict_call(duk_context * ctx)
{
	return duk_is_strict_call(ctx);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_string(duk_context * ctx, duk_idx_t index)
{
	return duk_is_string(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_thread(duk_context * ctx, duk_idx_t index)
{
	return duk_is_thread(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_undefined(duk_context * ctx, duk_idx_t index)
{
	return duk_is_undefined(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_is_valid_index(duk_context * ctx, duk_idx_t index)
{
	return duk_is_valid_index(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_join(duk_context * ctx, duk_idx_t count)
{
	duk_join(ctx, count);
}

WRAPPED_EXPORT_CALL void public_duk_json_decode(duk_context * ctx, duk_idx_t index)
{
	duk_json_decode(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_json_encode(duk_context * ctx, duk_idx_t index)
{
	return duk_json_encode(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_log_va(duk_context * ctx, duk_int_t level, const char * fmt, va_list ap)
{
	duk_log_va(ctx, level, fmt, ap);
}

WRAPPED_EXPORT_CALL void public_duk_map_string(duk_context * ctx, duk_idx_t index, duk_map_char_function callback, void * udata)
{
	duk_map_string(ctx, index, callback, udata);
}

WRAPPED_EXPORT_CALL void public_duk_new(duk_context * ctx, duk_idx_t nargs)
{
	duk_new(ctx, nargs);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_next(duk_context * ctx, duk_idx_t enum_index, duk_bool_t get_value)
{
	return duk_next(ctx, enum_index, get_value);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_normalize_index(duk_context * ctx, duk_idx_t index)
{
	return duk_normalize_index(ctx, index);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcall(duk_context * ctx, duk_idx_t nargs)
{
	return duk_pcall(ctx, nargs);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcall_method(duk_context * ctx, duk_idx_t nargs)
{
	return duk_pcall_method(ctx, nargs);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcall_prop(duk_context * ctx, duk_idx_t obj_index, duk_idx_t nargs)
{
	return duk_pcall_prop(ctx, obj_index, nargs);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile(duk_context * ctx, duk_uint_t flags)
{
	return duk_pcompile(ctx, flags);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile_file(duk_context * ctx, duk_uint_t flags, const char * path)
{
	return duk_pcompile_file(ctx, flags, path);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile_lstring(duk_context * ctx, duk_uint_t flags, const char * src, duk_size_t len)
{
	return duk_pcompile_lstring(ctx, flags, src, len);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile_lstring_filename(duk_context * ctx, duk_uint_t flags, const char * src, duk_size_t len)
{
	return duk_pcompile_lstring_filename(ctx, flags, src, len);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile_string(duk_context * ctx, duk_uint_t flags, const char * src)
{
	return duk_pcompile_string(ctx, flags, src);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_pcompile_string_filename(duk_context * ctx, duk_uint_t flags, const char * src)
{
	return duk_pcompile_string_filename(ctx, flags, src);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval(duk_context * ctx)
{
	return duk_peval(ctx);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_file(duk_context * ctx, const char * path)
{
	return duk_peval_file(ctx, path);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_file_noresult(duk_context * ctx, const char * path)
{
	return duk_peval_file_noresult(ctx, path);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_lstring(duk_context * ctx, const char * src, duk_size_t len)
{
	return duk_peval_lstring(ctx, src, len);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_lstring_noresult(duk_context * ctx, const char * src, duk_size_t len)
{
	return duk_peval_lstring_noresult(ctx, src, len);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_noresult(duk_context * ctx)
{
	return duk_peval_noresult(ctx);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_string(duk_context * ctx, const char * src)
{
	return duk_peval_string(ctx, src);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_peval_string_noresult(duk_context * ctx, const char * src)
{
	return duk_peval_string_noresult(ctx, src);
}

WRAPPED_EXPORT_CALL void public_duk_pop(duk_context * ctx)
{
	duk_pop(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_pop_2(duk_context * ctx)
{
	duk_pop_2(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_pop_3(duk_context * ctx)
{
	duk_pop_3(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_pop_n(duk_context * ctx, duk_idx_t count)
{
	duk_pop_n(ctx, count);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_array(duk_context * ctx)
{
	return duk_push_array(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_boolean(duk_context * ctx, duk_bool_t val)
{
	duk_push_boolean(ctx, val);
}

WRAPPED_EXPORT_CALL void * public_duk_push_buffer(duk_context * ctx, duk_size_t size, duk_bool_t dynamic)
{
	return duk_push_buffer(ctx, size, dynamic);
}

WRAPPED_EXPORT_CALL void public_duk_push_context_dump(duk_context * ctx)
{
	duk_push_context_dump(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_current_function(duk_context * ctx)
{
	duk_push_current_function(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_current_thread(duk_context * ctx)
{
	duk_push_current_thread(ctx);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_c_function(duk_context * ctx, duk_c_function func, duk_idx_t nargs)
{
	return duk_push_c_function(ctx, func, nargs);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_c_lightfunc(duk_context * ctx, duk_c_function func, duk_idx_t nargs, duk_idx_t length, duk_int_t magic)
{
	return duk_push_c_lightfunc(ctx, func, nargs, length, magic);
}

WRAPPED_EXPORT_CALL void * public_duk_push_dynamic_buffer(duk_context * ctx, duk_size_t size)
{
	return duk_push_dynamic_buffer(ctx, size);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_error_object_va(duk_context * ctx, duk_errcode_t err_code, const char * fmt, va_list ap)
{
	return duk_push_error_object_va(ctx, err_code, fmt, ap);
}

WRAPPED_EXPORT_CALL void public_duk_push_false(duk_context * ctx)
{
	duk_push_false(ctx);
}

WRAPPED_EXPORT_CALL void * public_duk_push_fixed_buffer(duk_context * ctx, duk_size_t size)
{
	return duk_push_fixed_buffer(ctx, size);
}

WRAPPED_EXPORT_CALL void public_duk_push_global_object(duk_context * ctx)
{
	duk_push_global_object(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_global_stash(duk_context * ctx)
{
	duk_push_global_stash(ctx);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_heapptr(duk_context * ctx, void * ptr)
{
	return duk_push_heapptr(ctx, ptr);
}

WRAPPED_EXPORT_CALL void public_duk_push_heap_stash(duk_context * ctx)
{
	duk_push_heap_stash(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_int(duk_context * ctx, duk_int_t val)
{
	duk_push_int(ctx, val);
}

WRAPPED_EXPORT_CALL const char * public_duk_push_lstring(duk_context * ctx, const char * str, duk_size_t len)
{
	return duk_push_lstring(ctx, str, len);
}

WRAPPED_EXPORT_CALL void public_duk_push_nan(duk_context * ctx)
{
	duk_push_nan(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_null(duk_context * ctx)
{
	duk_push_null(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_number(duk_context * ctx, duk_double_t val)
{
	duk_push_number(ctx, val);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_object(duk_context * ctx)
{
	return duk_push_object(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_pointer(duk_context * ctx, void * p)
{
	duk_push_pointer(ctx, p);
}

WRAPPED_EXPORT_CALL const char * public_duk_push_string(duk_context * ctx, const char * str)
{
	return duk_push_string(ctx, str);
}

WRAPPED_EXPORT_CALL const char * public_duk_push_string_file(duk_context * ctx, const char * path)
{
	return duk_push_string_file(ctx, path);
}

WRAPPED_EXPORT_CALL void public_duk_push_this(duk_context * ctx)
{
	duk_push_this(ctx);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_thread(duk_context * ctx)
{
	return duk_push_thread(ctx);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_push_thread_new_globalenv(duk_context * ctx)
{
	return duk_push_thread_new_globalenv(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_thread_stash(duk_context * ctx, duk_context * target_ctx)
{
	duk_push_thread_stash(ctx, target_ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_true(duk_context * ctx)
{
	duk_push_true(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_push_uint(duk_context * ctx, duk_uint_t val)
{
	duk_push_uint(ctx, val);
}

WRAPPED_EXPORT_CALL void public_duk_push_undefined(duk_context * ctx)
{
	duk_push_undefined(ctx);
}

WRAPPED_EXPORT_CALL const char * public_duk_push_vsprintf(duk_context * ctx, const char * fmt, va_list ap)
{
	return duk_push_vsprintf(ctx, fmt, ap);
}

WRAPPED_EXPORT_CALL void public_duk_put_function_list(duk_context * ctx, duk_idx_t obj_index, const duk_function_list_entry * funcs)
{
	duk_put_function_list(ctx, obj_index, funcs);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_put_global_string(duk_context * ctx, const char * key)
{
	return duk_put_global_string(ctx, key);
}

WRAPPED_EXPORT_CALL void public_duk_put_number_list(duk_context * ctx, duk_idx_t obj_index, const duk_number_list_entry * numbers)
{
	duk_put_number_list(ctx, obj_index, numbers);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_put_prop(duk_context * ctx, duk_idx_t obj_index)
{
	return duk_put_prop(ctx, obj_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_put_prop_index(duk_context * ctx, duk_idx_t obj_index, duk_uarridx_t arr_index)
{
	return duk_put_prop_index(ctx, obj_index, arr_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_put_prop_string(duk_context * ctx, duk_idx_t obj_index, const char * key)
{
	return duk_put_prop_string(ctx, obj_index, key);
}

WRAPPED_EXPORT_CALL void public_duk_put_var(duk_context * ctx)
{
	duk_put_var(ctx);
}

WRAPPED_EXPORT_CALL void * public_duk_realloc(duk_context * ctx, void * ptr, duk_size_t size)
{
	return duk_realloc(ctx, ptr, size);
}

WRAPPED_EXPORT_CALL void * public_duk_realloc_raw(duk_context * ctx, void * ptr, duk_size_t size)
{
	return duk_realloc_raw(ctx, ptr, size);
}

WRAPPED_EXPORT_CALL void public_duk_remove(duk_context * ctx, duk_idx_t index)
{
	duk_remove(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_replace(duk_context * ctx, duk_idx_t to_index)
{
	duk_replace(ctx, to_index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_require_boolean(duk_context * ctx, duk_idx_t index)
{
	return duk_require_boolean(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_require_buffer(duk_context * ctx, duk_idx_t index, duk_size_t * out_size)
{
	return duk_require_buffer(ctx, index, out_size);
}

WRAPPED_EXPORT_CALL duk_context * public_duk_require_context(duk_context * ctx, duk_idx_t index)
{
	return duk_require_context(ctx, index);
}

WRAPPED_EXPORT_CALL duk_c_function public_duk_require_c_function(duk_context * ctx, duk_idx_t index)
{
	return duk_require_c_function(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_require_heapptr(duk_context * ctx, duk_idx_t index)
{
	return duk_require_heapptr(ctx, index);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_require_int(duk_context * ctx, duk_idx_t index)
{
	return duk_require_int(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_require_lstring(duk_context * ctx, duk_idx_t index, duk_size_t * out_len)
{
	return duk_require_lstring(ctx, index, out_len);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_require_normalize_index(duk_context * ctx, duk_idx_t index)
{
	return duk_require_normalize_index(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_require_null(duk_context * ctx, duk_idx_t index)
{
	duk_require_null(ctx, index);
}

WRAPPED_EXPORT_CALL duk_double_t public_duk_require_number(duk_context * ctx, duk_idx_t index)
{
	return duk_require_number(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_require_object_coercible(duk_context * ctx, duk_idx_t index)
{
	duk_require_object_coercible(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_require_pointer(duk_context * ctx, duk_idx_t index)
{
	return duk_require_pointer(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_require_stack(duk_context * ctx, duk_idx_t extra)
{
	duk_require_stack(ctx, extra);
}

WRAPPED_EXPORT_CALL void public_duk_require_stack_top(duk_context * ctx, duk_idx_t top)
{
	duk_require_stack_top(ctx, top);
}

WRAPPED_EXPORT_CALL const char * public_duk_require_string(duk_context * ctx, duk_idx_t index)
{
	return duk_require_string(ctx, index);
}

WRAPPED_EXPORT_CALL duk_idx_t public_duk_require_top_index(duk_context * ctx)
{
	return duk_require_top_index(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_require_type_mask(duk_context * ctx, duk_idx_t index, duk_uint_t mask)
{
	duk_require_type_mask(ctx, index, mask);
}

WRAPPED_EXPORT_CALL duk_uint_t public_duk_require_uint(duk_context * ctx, duk_idx_t index)
{
	return duk_require_uint(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_require_undefined(duk_context * ctx, duk_idx_t index)
{
	duk_require_undefined(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_require_valid_index(duk_context * ctx, duk_idx_t index)
{
	duk_require_valid_index(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_resize_buffer(duk_context * ctx, duk_idx_t index, duk_size_t new_size)
{
	return duk_resize_buffer(ctx, index, new_size);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_safe_call(duk_context * ctx, duk_safe_call_function func, duk_idx_t nargs, duk_idx_t nrets)
{
	return duk_safe_call(ctx, func, nargs, nrets);
}

WRAPPED_EXPORT_CALL const char * public_duk_safe_to_lstring(duk_context * ctx, duk_idx_t index, duk_size_t * out_len)
{
	return duk_safe_to_lstring(ctx, index, out_len);
}

WRAPPED_EXPORT_CALL const char * public_duk_safe_to_string(duk_context * ctx, duk_idx_t index)
{
	return duk_safe_to_string(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_set_finalizer(duk_context * ctx, duk_idx_t index)
{
	duk_set_finalizer(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_set_global_object(duk_context * ctx)
{
	duk_set_global_object(ctx);
}

WRAPPED_EXPORT_CALL void public_duk_set_magic(duk_context * ctx, duk_idx_t index, duk_int_t magic)
{
	duk_set_magic(ctx, index, magic);
}

WRAPPED_EXPORT_CALL void public_duk_set_prototype(duk_context * ctx, duk_idx_t index)
{
	duk_set_prototype(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_set_top(duk_context * ctx, duk_idx_t index)
{
	duk_set_top(ctx, index);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_strict_equals(duk_context * ctx, duk_idx_t index1, duk_idx_t index2)
{
	return duk_strict_equals(ctx, index1, index2);
}

WRAPPED_EXPORT_CALL void public_duk_substring(duk_context * ctx, duk_idx_t index, duk_size_t start_char_offset, duk_size_t end_char_offset)
{
	duk_substring(ctx, index, start_char_offset, end_char_offset);
}

WRAPPED_EXPORT_CALL void public_duk_swap(duk_context * ctx, duk_idx_t index1, duk_idx_t index2)
{
	duk_swap(ctx, index1, index2);
}

WRAPPED_EXPORT_CALL void public_duk_swap_top(duk_context * ctx, duk_idx_t index)
{
	duk_swap_top(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_throw(duk_context * ctx)
{
	duk_throw(ctx);
}

WRAPPED_EXPORT_CALL duk_bool_t public_duk_to_boolean(duk_context * ctx, duk_idx_t index)
{
	return duk_to_boolean(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_to_buffer(duk_context * ctx, duk_idx_t index, duk_size_t * out_size)
{
	return duk_to_buffer(ctx, index, out_size);
}

WRAPPED_EXPORT_CALL void public_duk_to_defaultvalue(duk_context * ctx, duk_idx_t index, duk_int_t hint)
{
	duk_to_defaultvalue(ctx, index, hint);
}

WRAPPED_EXPORT_CALL void * public_duk_to_dynamic_buffer(duk_context * ctx, duk_idx_t index, duk_size_t * out_size)
{
	return duk_to_dynamic_buffer(ctx, index, out_size);
}

WRAPPED_EXPORT_CALL void * public_duk_to_fixed_buffer(duk_context * ctx, duk_idx_t index, duk_size_t * out_size)
{
	return duk_to_fixed_buffer(ctx, index, out_size);
}

WRAPPED_EXPORT_CALL duk_int_t public_duk_to_int(duk_context * ctx, duk_int_t index)
{
	return duk_to_int(ctx, index);
}

WRAPPED_EXPORT_CALL duk_int32_t public_duk_to_int32(duk_context * ctx, duk_idx_t index)
{
	return duk_to_int32(ctx, index);
}

WRAPPED_EXPORT_CALL const char * public_duk_to_lstring(duk_context * ctx, duk_idx_t index, duk_size_t * out_len)
{
	return duk_to_lstring(ctx, index, out_len);
}

WRAPPED_EXPORT_CALL void public_duk_to_null(duk_context * ctx, duk_idx_t index)
{
	duk_to_null(ctx, index);
}

WRAPPED_EXPORT_CALL duk_double_t public_duk_to_number(duk_context * ctx, duk_idx_t index)
{
	return duk_to_number(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_to_object(duk_context * ctx, duk_idx_t index)
{
	duk_to_object(ctx, index);
}

WRAPPED_EXPORT_CALL void * public_duk_to_pointer(duk_context * ctx, duk_idx_t index)
{
	return duk_to_pointer(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_to_primitive(duk_context * ctx, duk_idx_t index, duk_int_t hint)
{
	duk_to_primitive(ctx, index, hint);
}

WRAPPED_EXPORT_CALL const char * public_duk_to_string(duk_context * ctx, duk_idx_t index)
{
	return duk_to_string(ctx, index);
}

WRAPPED_EXPORT_CALL duk_uint_t public_duk_to_uint(duk_context * ctx, duk_idx_t index)
{
	return duk_to_uint(ctx, index);
}

WRAPPED_EXPORT_CALL duk_uint16_t public_duk_to_uint16(duk_context * ctx, duk_idx_t index)
{
	return duk_to_uint16(ctx, index);
}

WRAPPED_EXPORT_CALL duk_uint32_t public_duk_to_uint32(duk_context * ctx, duk_idx_t index)
{
	return duk_to_uint32(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_to_undefined(duk_context * ctx, duk_idx_t index)
{
	duk_to_undefined(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_trim(duk_context * ctx, duk_idx_t index)
{
	duk_trim(ctx, index);
}

WRAPPED_EXPORT_CALL void public_duk_xcopy_top(duk_context * to_ctx, duk_context * from_ctx, duk_idx_t count)
{
	duk_xcopy_top(to_ctx, from_ctx, count);
}

WRAPPED_EXPORT_CALL void public_duk_xmove_top(duk_context * to_ctx, duk_context * from_ctx, duk_idx_t count)
{
	duk_xmove_top(to_ctx, from_ctx, count);
}
